FROM python:3.12-slim

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

WORKDIR /app

RUN apt-get update && apt-get install -y --no-install-recommends \
    curl \
    && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY ./proto/ /app/proto/
COPY ./contracts/ /app/contracts/
COPY main_service ./main_service

CMD ["uvicorn", "main_service.main:app", "--host", "0.0.0.0", "--port", "8000"]