# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: webhook.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'webhook.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rwebhook.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"e\n\x0eWebhookPayload\x12\x0e\n\x06job_id\x18\x01 \x01(\x03\x12\x12\n\njob_status\x18\x02 \x01(\t\x12/\n\x0b\x66inished_at\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"n\n\x12SendWebhookRequest\x12\x12\n\nwebhook_id\x18\x01 \x01(\x03\x12\x12\n\ntarget_url\x18\x02 \x01(\t\x12 \n\x07payload\x18\x03 \x01(\x0b\x32\x0f.WebhookPayload\x12\x0e\n\x06secret\x18\x04 \x01(\t\"H\n\x13SendWebhookResponse\x12\x12\n\nwebhook_id\x18\x01 \x01(\x03\x12\x0e\n\x06status\x18\x02 \x01(\t\x12\r\n\x05\x65rror\x18\x03 \x01(\t2I\n\rWebhookSender\x12\x38\n\x0bSendWebhook\x12\x13.SendWebhookRequest\x1a\x14.SendWebhookResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'webhook_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_WEBHOOKPAYLOAD']._serialized_start=50
  _globals['_WEBHOOKPAYLOAD']._serialized_end=151
  _globals['_SENDWEBHOOKREQUEST']._serialized_start=153
  _globals['_SENDWEBHOOKREQUEST']._serialized_end=263
  _globals['_SENDWEBHOOKRESPONSE']._serialized_start=265
  _globals['_SENDWEBHOOKRESPONSE']._serialized_end=337
  _globals['_WEBHOOKSENDER']._serialized_start=339
  _globals['_WEBHOOKSENDER']._serialized_end=412
# @@protoc_insertion_point(module_scope)
