from enum import Enum

class ExceptionCode(str, Enum):
    JOB_NOT_FOUND = "JOB_NOT_FOUND"
    WEBHOOK_NOT_FOUND = "WEBHOOK_NOT_FOUND"
    JOB_CREATE_ERROR = "JOB_CREATE_ERROR" 
    WEBHOOK_CREATE_ERROR = "WEBHOOK_CREATE_ERROR" 
    WEBHOOK_DELETE_ERROR = "WEBHOOK_DELETE_ERROR"